[application]

[bundle]
identifier = "com.mostovoi"
publisher = "PMostovoi"

[web.app]

# HTML title tag content
title = "monitoring-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
    "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css"
]

# Additional JavaScript files
script = ["https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
