POST http://localhost:3311/lora
Authorization: Bearer ZFj6GzdbLoLT3v2shaVq5iroGViEHglsx3pjXCc2eDbIgOib6sZrwF0q8ibxBIDS
Content-Type: application/json

{
  "time": "2025-10-30T10:08:31.234567Z",
  "deviceInfo": {
    "deviceName": "test_tracker",
    "devEui": "A84041FFFF0ABCDEf"
  },
  "data": "AzkDaVTjOMEbZP4/"
}

###

POST http://localhost:3311/last_positions
Content-Type: application/json

{
  "tracker_id" : "A84041FFFF0ABCDE",
  "tracker_name" : "test_tracker",
  "tail": 1
}

###

POST http://localhost:3311/last_positions
Content-Type: application/json

{
  "tracker_id" : "70b3d57ed00653c7",
  "tracker_name" : "FRA2455",
  "tail": 1
}



