stages:
  - build

build-macos-windows:
  stage: build
  image: rust:latest
  before_script:
    - cargo install dioxus-cli --force


    - rustup target add x86_64-pc-windows-gnu
    - rustup target add x86_64-apple-darwin || true

  script:
    - echo "Building Dioxus project"
    - dx bundle --release
  artifacts:
    paths:
      - dist/
